from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from markitdown import MarkItDown

SUPPORTED_EXTENSIONS = (
    ".pdf",
    ".docx",
    ".pptx",
    ".xlsx",
    ".xls",
    ".html",
    ".htm",
    ".csv",
    ".tsv",
    ".json",
    ".xml",
    ".txt",
    ".md",
    ".rtf",
    ".epub",
    ".jpg",
    ".jpeg",
    ".png",
    ".gif",
    ".bmp",
    ".tif",
    ".tiff",
    ".webp",
)
DEFAULT_MAX_MB = 25.0


@dataclass(slots=True)
class ConversionReport:
    ok: bool
    input_path: str
    output_path: str | None
    title: str | None
    extension: str
    bytes_in: int
    chars_out: int
    markdown: str
    converter: str = "markitdown"
    plugins_enabled: bool = False

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class ReviewPack:
    created_at: str
    files: list[ConversionReport]
    markdown: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "created_at": self.created_at,
            "files": [item.to_dict() for item in self.files],
            "markdown": self.markdown,
        }


def supported_extensions() -> tuple[str, ...]:
    return SUPPORTED_EXTENSIONS


def validate_local_input(path: str | Path, *, max_mb: float = DEFAULT_MAX_MB) -> Path:
    candidate = Path(path).expanduser().resolve()
    if not candidate.exists():
        raise FileNotFoundError(f"File not found: {candidate}")
    if not candidate.is_file():
        raise ValueError(f"Expected a file, got: {candidate}")

    suffix = candidate.suffix.lower()
    if suffix not in SUPPORTED_EXTENSIONS:
        allowed = ", ".join(SUPPORTED_EXTENSIONS)
        raise ValueError(f"Unsupported extension '{suffix or '[none]'}'. Allowed: {allowed}")

    max_bytes = int(max_mb * 1024 * 1024)
    size = candidate.stat().st_size
    if size > max_bytes:
        raise ValueError(
            f"Refusing to convert {candidate.name}: {size} bytes exceeds max {max_bytes} bytes ({max_mb:g} MB)"
        )

    return candidate


def default_output_path(input_path: str | Path) -> Path:
    source = Path(input_path)
    return source.with_suffix(source.suffix + ".md")


def convert_file(
    path: str | Path,
    *,
    output_path: str | Path | None = None,
    max_mb: float = DEFAULT_MAX_MB,
    enable_plugins: bool = False,
) -> ConversionReport:
    source = validate_local_input(path, max_mb=max_mb)
    md = MarkItDown(enable_plugins=enable_plugins)
    result = md.convert_local(source, file_extension=source.suffix.lower())
    markdown = result.markdown.rstrip() + "\n"

    final_output: Path | None = None
    if output_path is not None:
        final_output = Path(output_path).expanduser().resolve()
        final_output.parent.mkdir(parents=True, exist_ok=True)
        final_output.write_text(markdown, encoding="utf-8")

    return ConversionReport(
        ok=True,
        input_path=str(source),
        output_path=str(final_output) if final_output else None,
        title=getattr(result, "title", None),
        extension=source.suffix.lower(),
        bytes_in=source.stat().st_size,
        chars_out=len(markdown),
        markdown=markdown,
        plugins_enabled=enable_plugins,
    )


def build_review_pack(reports: Iterable[ConversionReport]) -> ReviewPack:
    items = list(reports)
    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    parts = [
        "# Agent Review Pack",
        "",
        f"Generated: {now}",
        f"Files: {len(items)}",
        "",
        "This file was generated by agent-markitdown.",
        "",
    ]
    for index, report in enumerate(items, start=1):
        title = report.title or Path(report.input_path).name
        parts.extend(
            [
                f"## Document {index}: {title}",
                "",
                f"- Source: `{report.input_path}`",
                f"- Extension: `{report.extension}`",
                f"- Input bytes: {report.bytes_in}",
                f"- Extracted chars: {report.chars_out}",
                "",
                report.markdown.rstrip(),
                "",
            ]
        )
    markdown = "\n".join(parts).rstrip() + "\n"
    return ReviewPack(created_at=now, files=items, markdown=markdown)
